title: International Press journal BPAM author support
description: TeX related material for the manuscript preparation for the 
             International Press journal Beijing Journal of Pure and Applied Mathematics
             (BPAM)
show_downloads: true
theme: jekyll-theme-tactile
